apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openshift-kie-springboot
    version: v1
  name: openshift-kie-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openshift-kie-springboot
      version: v1
  template:
    metadata:
      labels:
        app: openshift-kie-springboot
        version: v1
    spec:
      serviceAccountName: openshift-kie-springboot
      containers:
        - env:
          - name: MAVEN_LOCAL_REPO
            value: "/root/.m2/repository"
          - name: MAVEN_SETTINGS_XML
            value: "/root/.m2/settings.xml"
          name: openshift-kie-springboot
          image: quickstarter/openshift-kie-springboot:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - curl
                - localhost:8080/liveness
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - curl
                - localhost:8080/readiness
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
          securityContext:
            privileged: false