apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openshift-kie-springboot
    version: v1
  name: openshift-kie-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openshift-kie-springboot
      version: v1
  template:
    metadata:
      labels:
        app: openshift-kie-springboot
        version: v1
    spec:
      serviceAccountName: openshift-kie-springboot
      securityContext:
        runAsUser: 1000170000
        runAsNonRoot: true
      containers:
        - env:
          - name: UPDATABLEKJAR
            value: "true"
          - name: KJARGAV
            value: org.kie.cloud:test-hacep-cloud-kjar:1.0.0
          - name: MAVEN_LOCAL_REPO
            value: /app/.m2/repository
          - name: MAVEN_MIRROR_URL
            value: http://nexus-nexus.192.168.99.133.nip.io/repository/maven-releases/
          - name: MAVEN_SETTINGS_XML
            value: /app/.m2/settings.xml
          name: openshift-kie-springboot
          image: quickstarter/openshift-kie-springboot:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
          securityContext:
            privileged: false