apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-kie-thorntail
  labels:
    app: openshift-kie-thorntail
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
      - secrets
      - serviceaccounts
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch